spring:
  datasource:
    url: jdbc:h2:mem:querydsl
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # 서버 실행시 테이블 drop -> insert
    properties:
      hibernate:
#        show_sql: true # sql system.out
        format_sql: true # sql log

  h2:
    console:
      enabled: true
      path: /h2-console

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace # parameter 보이기